FROM node:alpine as builder

WORKDIR /app

COPY package.json .

RUN npm init -y && npm install

COPY index.js .

ARG VERSION=1.0.1
ENV VERSION=$VERSION

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN apk add --no-cache nodejs

HEALTHCHECK --interval=10s --timeout=3s \
    CMD curl -f http://localhost:8080/ || exit 1

EXPOSE 80

CMD ["sh", "-c", "node /usr/share/nginx/html/index.js & nginx -g 'daemon off;'"]
